// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaAplicacaoBlazor.Data;

#nullable disable

namespace MinhaAplicacaoBlazor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702030403_AddTipoPessoaFormaContaBancaria")]
    partial class AddTipoPessoaFormaContaBancaria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.CategoriaFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CategoriasFornecedores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.ConfiguracaoCnab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("AgenciaDV")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("BancoCodigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("BancoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ContaDV")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Convenio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NomeConfiguracao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SequencialArquivo")
                        .HasColumnType("int");

                    b.Property<string>("VersaoLayoutArquivo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("VersaoLayoutLote")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("NomeConfiguracao")
                        .IsUnique();

                    b.ToTable("ConfiguracoesCnab");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.FormaLancamentoCnab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Segmentos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("FormasLancamentoCnab");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RemessaCnab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ConfiguracaoCnabId")
                        .HasColumnType("int");

                    b.Property<string>("ConteudoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NumeroSequencial")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuantidadePagamentos")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeRegistros")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("ConfiguracaoCnabId");

                    b.HasIndex("NomeArquivo");

                    b.HasIndex("NumeroSequencial");

                    b.ToTable("RemessasCnab");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RemessaCnabItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenciaDVFavorecido")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("AgenciaFavorecido")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("BancoFavorecido")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CPF_CNPJ_Favorecido")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("CodigoOcorrencia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContaDVFavorecido")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ContaFavorecido")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FolhaColaboradorItemId")
                        .HasColumnType("int");

                    b.Property<int?>("FolhaTutorItemId")
                        .HasColumnType("int");

                    b.Property<int>("FormaLancamentoCnabId")
                        .HasColumnType("int");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int?>("LancamentoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<string>("MensagemOcorrencia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeFavorecido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RemessaCnabId")
                        .HasColumnType("int");

                    b.Property<string>("SeuNumero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoChavePix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorPagamento")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("FolhaColaboradorItemId");

                    b.HasIndex("FolhaTutorItemId");

                    b.HasIndex("FormaLancamentoCnabId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("LancamentoFinanceiroId");

                    b.HasIndex("RemessaCnabId");

                    b.HasIndex("SeuNumero");

                    b.ToTable("RemessasCnabItens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RetornoCnab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConteudoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuantidadeItensProcessados")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeRegistros")
                        .HasColumnType("int");

                    b.Property<int?>("RemessaCnabId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RemessaCnabId");

                    b.ToTable("RetornosCnab");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RetornoCnabItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoOcorrencia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensagemOcorrencia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeFavorecido")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RemessaCnabItemId")
                        .HasColumnType("int");

                    b.Property<int>("RetornoCnabId")
                        .HasColumnType("int");

                    b.Property<string>("SeuNumero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatusProcessamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorPagamento")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("RemessaCnabItemId");

                    b.HasIndex("RetornoCnabId");

                    b.ToTable("RetornosCnabItens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CargaHorariaSemanal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TicketAlimentacao")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId")
                        .IsUnique()
                        .HasFilter("[ContaBancariaId] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("UnidadeId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberta");

                    b.HasKey("Id");

                    b.HasIndex("Mes", "Ano")
                        .IsUnique();

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoBanco")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Conta")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NomeBanco")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaHorariaTotal")
                        .HasColumnType("int");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("TotalAnos")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.EscalaAulaPratica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CursoTurma")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("MesAulaPratica")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalaLab")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("EscalasAulasPraticas");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LancamentoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberta");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("LancamentoFinanceiroId");

                    b.ToTable("FolhasColaboradores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaboradorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CargaHorariaSemanal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<decimal>("DecimoTerceiro")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DescontoINSS")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DescontoIR")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FeriasUmTerco")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("FolhaColaboradorId")
                        .HasColumnType("int");

                    b.Property<decimal>("HorasFalta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PlanoSaude")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PremiacaoFixa")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PremiacaoVariavel")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SalarioFamilia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SalarioLiquidoBase")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TicketAlimentacao")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalDescontos")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalProventos")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValeConsignadoFGTS")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorFaltas")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorReceberPix")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("FolhaColaboradorId");

                    b.ToTable("FolhasColaboradoresItens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LancamentoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberta");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("LancamentoFinanceiroId");

                    b.ToTable("FolhasTutores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Banco")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Conta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FolhaTutorId")
                        .HasColumnType("int");

                    b.Property<string>("NomeTitularConta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StatusPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalHorasNormais")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalHorasPraticas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAulaNormal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorAulaPratica")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorHoraNormal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorHoraPratica")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorTotalReceber")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("FolhaTutorId");

                    b.HasIndex("TutorId");

                    b.ToTable("FolhasTutoresItens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaFornecedorId")
                        .HasColumnType("int");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NomeContato")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaFornecedorId");

                    b.HasIndex("ContaBancariaId")
                        .IsUnique()
                        .HasFilter("[ContaBancariaId] IS NOT NULL");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Manual");

                    b.Property<int?>("OrigemId")
                        .HasColumnType("int");

                    b.Property<int>("PlanoContaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberto");

                    b.Property<string>("TipoDespesa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoLancamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("PlanoContaId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("LancamentosFinanceiros");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.PlanoConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PlanosContas");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Titulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorHoraAulaNormal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorHoraAulaPratica")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Titulacoes");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TitulacaoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId")
                        .IsUnique()
                        .HasFilter("[ContaBancariaId] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("CursoId");

                    b.HasIndex("TitulacaoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RemessaCnab", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Cnab.ConfiguracaoCnab", "ConfiguracaoCnab")
                        .WithMany()
                        .HasForeignKey("ConfiguracaoCnabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competencia");

                    b.Navigation("ConfiguracaoCnab");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RemessaCnabItem", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.FolhaColaboradorItem", "FolhaColaboradorItem")
                        .WithMany()
                        .HasForeignKey("FolhaColaboradorItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.FolhaTutorItem", "FolhaTutorItem")
                        .WithMany()
                        .HasForeignKey("FolhaTutorItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Cnab.FormaLancamentoCnab", "FormaLancamentoCnab")
                        .WithMany()
                        .HasForeignKey("FormaLancamentoCnabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", "LancamentoFinanceiro")
                        .WithMany()
                        .HasForeignKey("LancamentoFinanceiroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Cnab.RemessaCnab", "RemessaCnab")
                        .WithMany("Itens")
                        .HasForeignKey("RemessaCnabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolhaColaboradorItem");

                    b.Navigation("FolhaTutorItem");

                    b.Navigation("FormaLancamentoCnab");

                    b.Navigation("Fornecedor");

                    b.Navigation("LancamentoFinanceiro");

                    b.Navigation("RemessaCnab");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RetornoCnab", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Cnab.RemessaCnab", "RemessaCnab")
                        .WithMany()
                        .HasForeignKey("RemessaCnabId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RemessaCnab");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RetornoCnabItem", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Cnab.RemessaCnabItem", "RemessaCnabItem")
                        .WithMany()
                        .HasForeignKey("RemessaCnabItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Cnab.RetornoCnab", "RetornoCnab")
                        .WithMany("Itens")
                        .HasForeignKey("RetornoCnabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemessaCnabItem");

                    b.Navigation("RetornoCnab");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Colaborador", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.ContaBancaria", "ContaBancaria")
                        .WithOne()
                        .HasForeignKey("MinhaAplicacaoBlazor.Models.Colaborador", "ContaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaBancaria");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.EscalaAulaPratica", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaborador", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", "LancamentoFinanceiro")
                        .WithMany()
                        .HasForeignKey("LancamentoFinanceiroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competencia");

                    b.Navigation("LancamentoFinanceiro");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaboradorItem", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.FolhaColaborador", "FolhaColaborador")
                        .WithMany("Itens")
                        .HasForeignKey("FolhaColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("FolhaColaborador");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutor", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", "LancamentoFinanceiro")
                        .WithMany()
                        .HasForeignKey("LancamentoFinanceiroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competencia");

                    b.Navigation("LancamentoFinanceiro");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutorItem", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.FolhaTutor", "FolhaTutor")
                        .WithMany("Itens")
                        .HasForeignKey("FolhaTutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FolhaTutor");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Fornecedor", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.CategoriaFornecedor", "CategoriaFornecedor")
                        .WithMany()
                        .HasForeignKey("CategoriaFornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.ContaBancaria", "ContaBancaria")
                        .WithOne()
                        .HasForeignKey("MinhaAplicacaoBlazor.Models.Fornecedor", "ContaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaFornecedor");

                    b.Navigation("ContaBancaria");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinhaAplicacaoBlazor.Models.PlanoConta", "PlanoConta")
                        .WithMany()
                        .HasForeignKey("PlanoContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Competencia");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Fornecedor");

                    b.Navigation("PlanoConta");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Tutor", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.ContaBancaria", "ContaBancaria")
                        .WithOne()
                        .HasForeignKey("MinhaAplicacaoBlazor.Models.Tutor", "ContaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Curso", "Curso")
                        .WithMany("Tutores")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Titulacao", "Titulacao")
                        .WithMany("Tutores")
                        .HasForeignKey("TitulacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Unidade", "Unidade")
                        .WithMany("Tutores")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaBancaria");

                    b.Navigation("Curso");

                    b.Navigation("Titulacao");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RemessaCnab", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Cnab.RetornoCnab", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Curso", b =>
                {
                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaborador", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutor", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Titulacao", b =>
                {
                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Unidade", b =>
                {
                    b.Navigation("Tutores");
                });
#pragma warning restore 612, 618
        }
    }
}
