// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaAplicacaoBlazor.Data;

#nullable disable

namespace MinhaAplicacaoBlazor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705224130_AddCnabBtgGerenciamento")]
    partial class AddCnabBtgGerenciamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.CnabBtg.Data.CnabBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AuditoriaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BancoCadastroId")
                        .HasColumnType("int");

                    b.Property<string>("BancoCadastroNome")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CaminhoZip")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Convenio")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmpresaPagadora")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeBaseArquivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NsaFinal")
                        .HasColumnType("int");

                    b.Property<int>("NsaInicial")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeBoletos")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeSelecionada")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeTotalCompetencia")
                        .HasColumnType("int");

                    b.Property<bool>("SeparadoPorForma")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoGeracao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoPagamentoPrincipal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TotalCorrigidos")
                        .HasColumnType("int");

                    b.Property<int>("TotalInvalidos")
                        .HasColumnType("int");

                    b.Property<int>("TotalPendentes")
                        .HasColumnType("int");

                    b.Property<int>("TotalSelecionados")
                        .HasColumnType("int");

                    b.Property<int>("TotalValidos")
                        .HasColumnType("int");

                    b.Property<string>("TratamentoInvalidos")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("ValorTotalBoletos")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("ValorTotalCompetencia")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("ValorTotalGerado")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("ValorTotalInvalidos")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("ValorTotalSelecionado")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("GeradoEm");

                    b.ToTable("CnabBatches");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.CnabBtg.Data.CnabBatchPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoDestino")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("CnabBatchId")
                        .HasColumnType("int");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataCnab")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaLancamento")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrigemId")
                        .HasColumnType("int");

                    b.Property<string>("SegmentosGerados")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StatusCnab")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,2)");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CnabBatchId");

                    b.HasIndex("Origem", "OrigemId");

                    b.ToTable("CnabBatchPayments");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.CnabBtg.Data.CnabGeneratedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CnabBatchId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Nsa")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeOperacoes")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeRegistros")
                        .HasColumnType("int");

                    b.Property<bool>("TodasLinhas240")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("CnabBatchId");

                    b.ToTable("CnabGeneratedFiles");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.CnabBtg.Data.CnabSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmpresaPagadora")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UltimoNsa")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaPagadora")
                        .IsUnique();

                    b.ToTable("CnabSequences");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EntradaId")
                        .HasColumnType("int");

                    b.Property<int?>("FolhaFornecedorItemId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("FolhaFornecedorItemId");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PerfilId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Sistema")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.PerfilPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId", "Permissao")
                        .IsUnique();

                    b.ToTable("PerfilPermissoes");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.UsuarioPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concedida")
                        .HasColumnType("bit");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Permissao")
                        .IsUnique();

                    b.ToTable("UsuarioPermissoes");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeBanco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NomeBanco")
                        .IsUnique();

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.CategoriaFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CategoriasFornecedores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CargaHorariaSemanal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TicketAlimentacao")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId")
                        .IsUnique()
                        .HasFilter("[ContaBancariaId] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("UnidadeId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberta");

                    b.HasKey("Id");

                    b.HasIndex("Mes", "Ano")
                        .IsUnique();

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoBanco")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Conta")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("DigitoConta")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NomeBanco")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoChavePix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Nenhuma");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Corrente");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaHorariaTotal")
                        .HasColumnType("int");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("TotalAnos")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BancoId")
                        .HasColumnType("int");

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.EscalaAulaPratica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CursoTurma")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("MesAulaPratica")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalaLab")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("EscalasAulasPraticas");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LancamentoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberta");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("LancamentoFinanceiroId");

                    b.ToTable("FolhasColaboradores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaboradorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CargaHorariaSemanal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<decimal>("DecimoTerceiro")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DescontoINSS")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DescontoIR")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FeriasUmTerco")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("FolhaColaboradorId")
                        .HasColumnType("int");

                    b.Property<decimal>("HorasFalta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OutrosProventos")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PlanoSaude")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PremiacaoFixa")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PremiacaoVariavel")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SalarioFamilia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TicketAlimentacao")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalDescontos")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalProventos")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValeConsignadoFGTS")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorFaltas")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorReceberPix")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("FolhaColaboradorId");

                    b.ToTable("FolhasColaboradoresItens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LancamentoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberta");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("LancamentoFinanceiroId");

                    b.ToTable("FolhasFornecedores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaFornecedorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Banco")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("BancoPagadorId")
                        .HasColumnType("int");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Conta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FolhaFornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("NomeTitularConta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StatusPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorTotalPagar")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BancoPagadorId");

                    b.HasIndex("FolhaFornecedorId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("FolhasFornecedoresItens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LancamentoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberta");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("LancamentoFinanceiroId");

                    b.ToTable("FolhasTutores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Banco")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Conta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FolhaTutorId")
                        .HasColumnType("int");

                    b.Property<string>("NomeTitularConta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StatusPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalHorasNormais")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalHorasPraticas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAulaNormal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorAulaPratica")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorHoraNormal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorHoraPratica")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorTotalReceber")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("FolhaTutorId");

                    b.HasIndex("TutorId");

                    b.ToTable("FolhasTutoresItens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaFornecedorId")
                        .HasColumnType("int");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NomeContato")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PlanoContaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaFornecedorId");

                    b.HasIndex("ContaBancariaId")
                        .IsUnique()
                        .HasFilter("[ContaBancariaId] IS NOT NULL");

                    b.HasIndex("PlanoContaId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Manual");

                    b.Property<int?>("OrigemId")
                        .HasColumnType("int");

                    b.Property<int>("PlanoContaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aberto");

                    b.Property<string>("TipoDespesa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoLancamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("PlanoContaId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("LancamentosFinanceiros");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.PlanoConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PlanosContas");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.RegistroAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Alteracoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("RegistrosAuditoria");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Titulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorHoraAulaNormal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorHoraAulaPratica")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Titulacoes");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TitulacaoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId")
                        .IsUnique()
                        .HasFilter("[ContaBancariaId] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("CursoId");

                    b.HasIndex("TitulacaoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.CnabBtg.Data.CnabBatchPayment", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.CnabBtg.Data.CnabBatch", "CnabBatch")
                        .WithMany("Pagamentos")
                        .HasForeignKey("CnabBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CnabBatch");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.CnabBtg.Data.CnabGeneratedFile", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.CnabBtg.Data.CnabBatch", "CnabBatch")
                        .WithMany("Arquivos")
                        .HasForeignKey("CnabBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CnabBatch");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Arquivo", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Entrada", "Entrada")
                        .WithMany("Arquivos")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MinhaAplicacaoBlazor.Models.FolhaFornecedorItem", "FolhaFornecedorItem")
                        .WithMany("Arquivos")
                        .HasForeignKey("FolhaFornecedorItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Entrada");

                    b.Navigation("FolhaFornecedorItem");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.ApplicationUser", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Auth.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.PerfilPermissao", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Auth.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.UsuarioPermissao", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Auth.ApplicationUser", "Usuario")
                        .WithMany("Permissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Colaborador", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.ContaBancaria", "ContaBancaria")
                        .WithOne()
                        .HasForeignKey("MinhaAplicacaoBlazor.Models.Colaborador", "ContaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaBancaria");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Entrada", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("Competencia");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.EscalaAulaPratica", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaborador", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", "LancamentoFinanceiro")
                        .WithMany()
                        .HasForeignKey("LancamentoFinanceiroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competencia");

                    b.Navigation("LancamentoFinanceiro");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaboradorItem", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.FolhaColaborador", "FolhaColaborador")
                        .WithMany("Itens")
                        .HasForeignKey("FolhaColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("FolhaColaborador");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaFornecedor", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", "LancamentoFinanceiro")
                        .WithMany()
                        .HasForeignKey("LancamentoFinanceiroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competencia");

                    b.Navigation("LancamentoFinanceiro");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaFornecedorItem", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Banco", "BancoPagador")
                        .WithMany()
                        .HasForeignKey("BancoPagadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinhaAplicacaoBlazor.Models.FolhaFornecedor", "FolhaFornecedor")
                        .WithMany("Itens")
                        .HasForeignKey("FolhaFornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BancoPagador");

                    b.Navigation("FolhaFornecedor");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutor", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", "LancamentoFinanceiro")
                        .WithMany()
                        .HasForeignKey("LancamentoFinanceiroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competencia");

                    b.Navigation("LancamentoFinanceiro");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutorItem", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.FolhaTutor", "FolhaTutor")
                        .WithMany("Itens")
                        .HasForeignKey("FolhaTutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FolhaTutor");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Fornecedor", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.CategoriaFornecedor", "CategoriaFornecedor")
                        .WithMany()
                        .HasForeignKey("CategoriaFornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.ContaBancaria", "ContaBancaria")
                        .WithOne()
                        .HasForeignKey("MinhaAplicacaoBlazor.Models.Fornecedor", "ContaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.PlanoConta", "PlanoConta")
                        .WithMany()
                        .HasForeignKey("PlanoContaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaFornecedor");

                    b.Navigation("ContaBancaria");

                    b.Navigation("PlanoConta");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.LancamentoFinanceiro", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinhaAplicacaoBlazor.Models.PlanoConta", "PlanoConta")
                        .WithMany()
                        .HasForeignKey("PlanoContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Competencia");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Fornecedor");

                    b.Navigation("PlanoConta");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Tutor", b =>
                {
                    b.HasOne("MinhaAplicacaoBlazor.Models.ContaBancaria", "ContaBancaria")
                        .WithOne()
                        .HasForeignKey("MinhaAplicacaoBlazor.Models.Tutor", "ContaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MinhaAplicacaoBlazor.Models.Curso", "Curso")
                        .WithMany("Tutores")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Titulacao", "Titulacao")
                        .WithMany("Tutores")
                        .HasForeignKey("TitulacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaAplicacaoBlazor.Models.Unidade", "Unidade")
                        .WithMany("Tutores")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaBancaria");

                    b.Navigation("Curso");

                    b.Navigation("Titulacao");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.CnabBtg.Data.CnabBatch", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.ApplicationUser", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Auth.Perfil", b =>
                {
                    b.Navigation("Permissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Curso", b =>
                {
                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Entrada", b =>
                {
                    b.Navigation("Arquivos");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaColaborador", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaFornecedor", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaFornecedorItem", b =>
                {
                    b.Navigation("Arquivos");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.FolhaTutor", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Titulacao", b =>
                {
                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("MinhaAplicacaoBlazor.Models.Unidade", b =>
                {
                    b.Navigation("Tutores");
                });
#pragma warning restore 612, 618
        }
    }
}
